export const projects = [
  {
    title: 'E-learning - Landing page',
    description: "This reactjs project consists of a simple landing page featuring an e-learning website. The page is 100% responsive so that it adapts to all screen sizes and the user experience is always good.",
      image: '/images/1.png',
      tags: ['React', 'JavaScript'],
    source: 'https://github.com/Dev-Alex-H/E-Learning-Landing-Page',
    visit: 'https://clever-cobbler-5236d8.netlify.app/',
    id: 0,
  },
  {
    title: 'Giffs App',
    description: "GIFFS app is a react project that consists of the use of an API. This API gives us a list of gifs according to searches or trends, which are displayed with custom styles.",
      image: '/images/5.png',
      tags: ['React', 'JavaScript', 'Wouter'],
    source: 'https://github.com/Dev-Alex-H/GIFFS-app',
    visit: 'https://62ddcb340a983d322e1f4902--gleaming-scone-ea53f8.netlify.app/',
    id: 1,
  },
  {
    title: 'DevJobs App',
    description: "This is a frontend mentor challenge. It consists of a fully responsive devjobs web application that uses React. It has a modern user interface and user experience. The app implements autocomplete lookup using react hooks, has the function of looking up data in react, adds data filtering, uses the remixicon library, and has a modern design with CSS3.",
      image: '/images/3.png',
      tags: ['React', 'CSS3'],
      source: 'https://github.com/Dev-Alex-H/DevJobs-app',
      visit: 'https://glittering-lollipop-0c49b2.netlify.app/jobs',
    id: 2,
  },
  {
    title: 'Movies App',
    description: "Movies app is a react project that consists of the use of an API. This API gives us a list of movies according to searches or trends, which are displayed with custom styles.",
    image: '/images/6.png',
    tags: ['React', 'JS', 'React-Router'],
    source: 'https://github.com/Dev-Alex-H/Movies',
    visit: 'https://hopeful-haibt-a121ad.netlify.app',
    id: 3,
  },
  {
    title: 'Audio Yack',
    description: "It is my first project. This project is a simple landing page built with HTML, CSS, and JavaScript. It has a contemporary user interface with a simple style and easy access to the user.",
      image: '/images/7.png',
      tags: ['CSS3', 'JavaScript', 'HTML5'],
    source: 'https://github.com/Dev-Alex-H/LandingPage',
    visit: 'https://dev-alex-h.github.io/LandingPage/',
    id: 4
  },
  // {
  //   title: 'E-Commerce - Delivery food app',
  //   description:"Food delivery app ecommerce website with modern UI and UX. This project uses the redux toolkit, the remixicon library, uses react's useState hooks, useEffect hooks, useRef hooks, CSS3, the react slider to create carousels/slides, and pagination using react-paginate.",
  //   image: '/images/2.png',
  //   tags: ['React', 'JavaScript', 'CSS3'],
  //   source: 'https://github.com/Dev-Alex-H/React-delivery-app',
  //   visit: 'https://google.com',
  //   id: 5,
  // }, 
];
